<?php

namespace App\Models;

use App\Traits\InteractsWithMedia;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Storage;
use Spatie\MediaLibrary\HasMedia;

class Setting extends Model implements HasMedia
{

    use InteractsWithMedia ;
    protected static string $cacheName = 'settings';


    protected $fillable = ['name', 'description', 'phone', 'email', 'social', 'location', 'whatsapp'];

    protected $casts = [
        'description' => 'json',
        'phone' => 'json',
        'email' => 'json',
        'social' => 'json',
        'whatsapp' => 'json',
        'location' => 'json',
    ];

    protected $appends = ['logo_link'];

    public static function staticsData()
    {

        return Cache::rememberForever(static::$cacheName, function () {
            return static::first();
        });
    }

    protected static function boot()
    {
        static::updated(function () {
            Cache::forget(static::$cacheName);
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function meta(): MorphOne
    {
        return $this->morphOne(Meta::class, 'model');
    }

    public function getLogoLinkAttribute(): string
    {
        return Storage::url($this->logo);
    }
}
